/* This file is generated by MATLAB, please do not edit.
 * -- generated 07-Dec-2015 by generateC.m -- */

#include "matlab_include.h"


struct Int32Vect3 matlab_noise_distribution = { .x = 16, .y = 16, .z = 16 };

struct Int32Vect3 matlab_disturbance_distribution = { .x = 80364, .y = 80364, .z = 80364 };

