/* This file is generated by MATLAB, please do not edit.
 * -- generated 24-Nov-2015 by guidance_optimal.m -- */

#include "matlab_include.h"


struct Int32Vect2 matlab_guidance_gain = {.x = 23170, .y = 29438};
/* optimal gain for forward and lateral guidance: */
struct Int32Vect2 matlab_guidance_gain_fwd = {.x = 23170, .y = 29438};