/* This file is generated by MATLAB, please do not edit.
 * -- generated 23-Nov-2015 -- */

#include "matlab_include.h"


const uint8_t INT32_MATLAB_FRAC = 14;


/* V = 0.4 */
int32_t matlab_pitch_equilibrium_v04 = 1042;
int32_t matlab_throttle_equilibrium_v04 = 1265;
struct Int32Vect2 matlab_pitch_matrix_v04 = {.x = 85, .y = -21};
struct Int32Vect2 matlab_throttle_matrix_v04 = {.x = 2, .y = -85};

/* V = 0.8 */
int32_t matlab_pitch_equilibrium_v08 = 922;
int32_t matlab_throttle_equilibrium_v08 = 1216;
struct Int32Vect2 matlab_pitch_matrix_v08 = {.x = 62, .y = -24};
struct Int32Vect2 matlab_throttle_matrix_v08 = {.x = -13, .y = -85};

/* V = 1.2 */
int32_t matlab_pitch_equilibrium_v12 = 661;
int32_t matlab_throttle_equilibrium_v12 = 1092;
struct Int32Vect2 matlab_pitch_matrix_v12 = {.x = 99, .y = -70};
struct Int32Vect2 matlab_throttle_matrix_v12 = {.x = -24, .y = -83};

/* V = 2.5 */
int32_t matlab_pitch_equilibrium_v25 = 427;
int32_t matlab_throttle_equilibrium_v25 = 959;
struct Int32Vect2 matlab_pitch_matrix_v25 = {.x = 38, .y = -26};
struct Int32Vect2 matlab_throttle_matrix_v25 = {.x = -57, .y = -65};

/* V = 5.0 */
int32_t matlab_pitch_equilibrium_v50 = 167;
int32_t matlab_throttle_equilibrium_v50 = 999;
struct Int32Vect2 matlab_pitch_matrix_v50 = {.x = 12, .y = -15};
struct Int32Vect2 matlab_throttle_matrix_v50 = {.x = -184, .y = -33};
