/* This file is generated by MATLAB, please do not edit.
 * -- generated 24-Nov-2015 by speedThrustControl.m -- */

#include "matlab_include.h"


/* V = 0.4 */
int32_t matlab_pitch_equilibrium_v04 = 21274;
int32_t matlab_throttle_equilibrium_v04 = 1480021;
struct Int32Vect2 matlab_pitch_matrix_v04 = {.x = 1739, .y = -436};
struct Int32Vect2 matlab_throttle_matrix_v04 = {.x = 2103, .y = -100049};

/* V = 0.8 */
int32_t matlab_pitch_equilibrium_v08 = 18829;
int32_t matlab_throttle_equilibrium_v08 = 1422677;
struct Int32Vect2 matlab_pitch_matrix_v08 = {.x = 1259, .y = -485};
struct Int32Vect2 matlab_throttle_matrix_v08 = {.x = -14925, .y = -99444};

/* V = 1.2 */
int32_t matlab_pitch_equilibrium_v12 = 13504;
int32_t matlab_throttle_equilibrium_v12 = 1277952;
struct Int32Vect2 matlab_pitch_matrix_v12 = {.x = 2031, .y = -1423};
struct Int32Vect2 matlab_throttle_matrix_v12 = {.x = -28124, .y = -97341};

/* V = 2.5 */
int32_t matlab_pitch_equilibrium_v25 = 8723;
int32_t matlab_throttle_equilibrium_v25 = 1122031;
struct Int32Vect2 matlab_pitch_matrix_v25 = {.x = 778, .y = -525};
struct Int32Vect2 matlab_throttle_matrix_v25 = {.x = -66989, .y = -76319};

/* V = 5.0 */
int32_t matlab_pitch_equilibrium_v50 = 3403;
int32_t matlab_throttle_equilibrium_v50 = 1169579;
struct Int32Vect2 matlab_pitch_matrix_v50 = {.x = 241, .y = -312};
struct Int32Vect2 matlab_throttle_matrix_v50 = {.x = -214971, .y = -38741};

