/* This file is generated by MATLAB, please do not edit.
 * -- generated 07-Dec-2015 by speedThrustControl.m -- */

#include "matlab_include.h"


/* V = 0.4 */
int32_t matlab_pitch_equilibrium_v04 = 21274;
int32_t matlab_throttle_equilibrium_v04 = 11563;
struct Int32Vect2 matlab_pitch_matrix_v04 = {.x = 1739, .y = -436};
struct Int32Vect2 matlab_throttle_matrix_v04 = {.x = 16, .y = -782};

/* V = 0.8 */
int32_t matlab_pitch_equilibrium_v08 = 18829;
int32_t matlab_throttle_equilibrium_v08 = 11115;
struct Int32Vect2 matlab_pitch_matrix_v08 = {.x = 1259, .y = -485};
struct Int32Vect2 matlab_throttle_matrix_v08 = {.x = -117, .y = -777};

/* V = 1.2 */
int32_t matlab_pitch_equilibrium_v12 = 13504;
int32_t matlab_throttle_equilibrium_v12 = 9984;
struct Int32Vect2 matlab_pitch_matrix_v12 = {.x = 2031, .y = -1423};
struct Int32Vect2 matlab_throttle_matrix_v12 = {.x = -220, .y = -760};

/* V = 2.5 */
int32_t matlab_pitch_equilibrium_v25 = 8723;
int32_t matlab_throttle_equilibrium_v25 = 8766;
struct Int32Vect2 matlab_pitch_matrix_v25 = {.x = 778, .y = -525};
struct Int32Vect2 matlab_throttle_matrix_v25 = {.x = -523, .y = -596};

/* V = 5.0 */
int32_t matlab_pitch_equilibrium_v50 = 3403;
int32_t matlab_throttle_equilibrium_v50 = 9137;
struct Int32Vect2 matlab_pitch_matrix_v50 = {.x = 241, .y = -312};
struct Int32Vect2 matlab_throttle_matrix_v50 = {.x = -1679, .y = -303};

